# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'learnios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'AnimatedCollectionViewLayout'
  pod 'Firebase/Firestore'
  pod ‘FMDB’,’~> 2.6.2’
  # Pods for learnios

  target 'learniosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'learniosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
